Feat: added comment support and formatted code
cute-engineewing/monkelisp pull request #3
Opened 2021-05-10 00:07 UTC by Abb1x

I added one-line comments support!

2021-05-10 08:53 UTC, Keyboard-Slayer requested changes

2021-05-10 08:53 UTC, Keyboard-Slayer commented on src/reader.c
> +		if (content[i] == ';')
You shouldn't delete the comment during the lexing phase, you should rather put it in one block of comment

for example if I follow your example :  
```scheme
(+ 1 2 3) ;  hello comment world!
```

the ast will look like this

`{"+", "1", "2", "3", ";  hello comment world!"};`

2021-05-10 08:53 UTC, Keyboard-Slayer commented on tests/test_reader.c
> +	vec_foreach(&tokens, t, i) { assert_string_equal(expected[i], t); }
I made a mistake on how I did the first test, I'll at(@) you when I'll fix it. 

I'm looping on the result and not on the template

2021-05-10 08:53 UTC, Keyboard-Slayer commented on tests/test_reader.c
> +	tokens = tokenize("(+ 1 2 3) ; hello comment world!\n");
You should write test on other configurations such as:

```scheme 
; test \\n (+ 1 2 3)
```

```scheme 
; test
(+ 1 2 3) 
```

```scheme 
(+ 1 2 3)
; test
```

2021-05-10 11:30 UTC, Abb1x commented on src/reader.c
> +		if (content[i] == ';')
What's the point of not removing them? They're ignored anyway

2021-05-10 11:38 UTC, Keyboard-Slayer commented on src/reader.c
> +		if (content[i] == ';')
It's easier for testing. If we make mistakes we can troubleshot it easily.

2021-05-12 12:53 UTC, Abb1x commented
:sweat:

2021-05-12 12:53 UTC, Keyboard-Slayer commented
Well, you went trough @Keyboard-Slayer 's coding style *sueur*
And you survived :sweat_smile:

2021-05-12 12:54 UTC, merged